{{- if .Values.check_kube_proxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: check-node-groups
data:
  node-groups.sh: |- {{ .Files.Get "checks/node-groups.sh" | nindent 4 }}
    {{- end }}