{{- if .Values.check_kube_proxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: check-loadbalancer-svc
data:
  loadbalancer-svc.sh: |- {{ .Files.Get "checks/loadbalancer-svc.sh" | nindent 4 }}
  loadbalancer-manifests.yaml: |- {{ .Files.Get "checks/res/loadbalancer-manifests.yaml" | nindent 4 }}
{{- end }}