{{- if .Values.check_cloudwatch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: check-cloudwatch
spec:
  template:
    spec:
      serviceAccountName: checks
      containers:
        - name: check-cloudwatch
          image: bitnami/kubectl:1.26
          workingDir: /checks
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          command: ["/bin/bash", "-c"]
          args:
            - "cp /conf/cloudwatch.sh ./ && chmod u+x cloudwatch.sh && ./cloudwatch.sh"
          volumeMounts:
            - mountPath: /conf
              name: config
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: check-cloudwatch
  backoffLimit: 0
  podFailurePolicy:
    rules:
      - action: FailJob
        onExitCodes:
          operator: In
          values: [ 1 ]
{{- end }}