{{- if .Values.check_csi.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: check-csi
spec:
  template:
    spec:
      serviceAccountName: checks
      containers:
        - name: check-csi
          image: bitnami/kubectl:1.26
          workingDir: /checks
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          command: ["/bin/bash", "-c"]
          args:
            - "cp /conf/csi* ./ && chmod u+x csi*.sh && CHECK_MODE={{ .Values.check_csi.checkMode }} ./csi.sh"
          volumeMounts:
            - mountPath: /conf
              name: config
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: check-csi
  backoffLimit: 0
  podFailurePolicy:
    rules:
      - action: FailJob
        onExitCodes:
          operator: In
          values: [ 1 ]
{{- end }}