kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: checks
rules:
  - apiGroups: [ "apps" ] # "" indicates the core API group
    resources: [ "*" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apiextensions.k8s.io" ] # "" indicates the core API group
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apiregistration.k8s.io" ]
    resources: [ "apiservices" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csidrivers" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "watch", "list" ]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: checks
rules:
  - apiGroups: [ "apps" ] # "" indicates the core API group
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "*" ]
    verbs: [ "*" ]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: checks
automountServiceAccountToken: true
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: checks
subjects:
  - name: checks
    kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: checks
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: checks
subjects:
  - name: checks
    kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: checks
  apiGroup: rbac.authorization.k8s.io