apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-checks
  labels:
    app.kubernetes.io/name: lb-checks
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lb-checks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lb-checks
    spec:
      containers:
        - name: echo-server
          image: ealen/echo-server:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb-checks
spec:
  selector:
    app.kubernetes.io/name: lb-checks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
